#!/bin/bash

set -e

verbose() {
	! test -z "$VERBOSE"
}

verbose && echo "Running tests..."
tools/test

verbose && echo "Formatting code..."
tools/format

verbose && echo "Measuring line lengths..."
tools/measure

# SITE_DIR is the final location where we want generated content to be
SITE_DIR="public"

# GENERATE_DIR is where the content will be generated initially
GENERATE_DIR="$(mktemp -d)"

function cleanup() {
  rm -rf "$GENERATE_DIR"
}
trap cleanup EXIT

verbose && echo "Generating HTML to $GENERATE_DIR..."
tools/generate $GENERATE_DIR

verbose && echo "Copying $GENERATE_DIR to $SITE_DIR"
cp -rf "${GENERATE_DIR}/." "$SITE_DIR"
